// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError('Firebase no está configurado para Linux.');

      default:
        throw UnsupportedError('Plataforma no soportada.');
    }
  }

  // Si decides compilar en Android, necesitarás generar sus credenciales en la consola de Firebase
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TU_API_KEY',
    appId: 'TU_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'hospital-f1a95',
    storageBucket: 'hospital-f1a95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TU_API_KEY',
    appId: 'TU_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'hospital-f1a95',
    storageBucket: 'hospital-f1a95.firebasestorage.app',
    iosBundleId: 'TU_BUNDLE_ID',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFXckfKmY50wElGAZuWe0ah4SsZNZC6E',
    appId: '1:803247250373:web:29dc1aa528562b728289ac',
    messagingSenderId: '803247250373',
    projectId: 'hospital-f1a95',
    authDomain: 'hospital-f1a95.firebaseapp.com',
    storageBucket: 'hospital-f1a95.firebasestorage.app',
    measurementId: 'G-H3GHVF8MCD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_API_KEY',
    appId: 'TU_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'hospital-f1a95',
    storageBucket: 'hospital-f1a95.firebasestorage.app',
    iosBundleId: 'TU_BUNDLE_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFXckfKmY50wElGAZuWe0ah4SsZNZC6E',
    appId: '1:803247250373:web:29dc1aa528562b728289ac',
    messagingSenderId: '803247250373',
    projectId: 'hospital-f1a95',
    authDomain: 'hospital-f1a95.firebaseapp.com',
    storageBucket: 'hospital-f1a95.firebasestorage.app',
  );
}
